export const WhaleSpaceConstants = {
    GET_TOKEN_GENERAL_REQUEST: 'GET_TOKEN_GENERAL_REQUEST',
    GET_TOKEN_GENERAL_SUCCESS: 'GET_TOKEN_GENERAL_SUCCESS',
    GET_TOKEN_GENERAL_FAILURE: 'GET_TOKEN_GENERAL_FAILURE',

    GET_TOP_WALLET_REQUEST: 'GET_TOP_WALLET_REQUEST',
    GET_TOP_WALLET_SUCCESS: 'GET_TOP_WALLET_SUCCESS',
    GET_TOP_WALLET_FAILURE: 'GET_TOP_WALLET_FAILURE',

    GET_TOP_WALLET_TOKEN_CHANGE_LOGS_REQUEST: 'GET_TOP_WALLET_TOKEN_CHANGE_LOGS_REQUEST',
    GET_TOP_WALLET_TOKEN_CHANGE_LOGS_SUCCESS: 'GET_TOP_WALLET_TOKEN_CHANGE_LOGS_SUCCESS',
    GET_TOP_WALLET_TOKEN_CHANGE_LOGS_FAILURE: 'GET_TOP_WALLET_TOKEN_CHANGE_LOGS_FAILURE',

    GET_TOKEN_DISTRIBUTION_REQUEST: 'GET_TOKEN_DISTRIBUTION_REQUEST',
    GET_TOKEN_DISTRIBUTION_SUCCESS: 'GET_TOKEN_DISTRIBUTION_SUCCESS',
    GET_TOKEN_DISTRIBUTION_FAILURE: 'GET_TOKEN_DISTRIBUTION_FAILURE',
}