export const WhaleSpaceConstants = {
    GET_TOKEN_INFOMATION_REQUEST: 'GET_TOKEN_INFOMATION_REQUEST',
    GET_TOKEN_INFOMATION_SUCCESS: 'GET_TOKEN_INFOMATION_SUCCESS',
    GET_TOKEN_INFOMATION_FAILURE: 'GET_TOKEN_INFOMATION_FAILURE',

    GET_TOP_WHALE_WALLETS_REQUEST: 'GET_TOP_WHALE_WALLETS_REQUEST',
    GET_TOP_WHALE_WALLETS_SUCCESS: 'GET_TOP_WHALE_WALLETS_SUCCESS',
    GET_TOP_WHALE_WALLETS_FAILURE: 'GET_TOP_WHALE_WALLETS_FAILURE',

    GET_TOP_WALLET_TOKEN_CHANGE_LOGS_REQUEST: 'GET_TOP_WALLET_TOKEN_CHANGE_LOGS_REQUEST',
    GET_TOP_WALLET_TOKEN_CHANGE_LOGS_SUCCESS: 'GET_TOP_WALLET_TOKEN_CHANGE_LOGS_SUCCESS',
    GET_TOP_WALLET_TOKEN_CHANGE_LOGS_FAILURE: 'GET_TOP_WALLET_TOKEN_CHANGE_LOGS_FAILURE',

    GET_TOKEN_DISTRIBUTION_REQUEST: 'GET_TOKEN_DISTRIBUTION_REQUEST',
    GET_TOKEN_DISTRIBUTION_SUCCESS: 'GET_TOKEN_DISTRIBUTION_SUCCESS',
    GET_TOKEN_DISTRIBUTION_FAILURE: 'GET_TOKEN_DISTRIBUTION_FAILURE',
}