export const WalletTypeConstants = {
    GET_TOKEN_GENERAL_REQUEST: 'GET_TOKEN_GENERAL_REQUEST',
    GET_TOKEN_GENERAL_SUCCESS: 'GET_TOKEN_GENERAL_SUCCESS',
    GET_TOKEN_GENERAL_FAILURE: 'GET_TOKEN_GENERAL_FAILURE',

    GET_WALLET_TYPE_REQUEST: 'GET_WALLET_TYPE_REQUEST',
    GET_WALLET_TYPE_SUCCESS: 'GET_WALLET_TYPE_SUCCESS',
    GET_WALLET_TYPE_FAILURE: 'GET_WALLET_TYPE_FAILURE'
}