export const RelationGraphConstants = {

    GET_WALLET_TYPE_REQUEST: 'GET_WALLET_TYPE_REQUEST',
    GET_WALLET_TYPE_SUCCESS: 'GET_WALLET_TYPE_SUCCESS',
    GET_WALLET_TYPE_FAILURE: 'GET_WALLET_TYPE_FAILURE',

    GET_CLOSE_RELATION_EDGES_REQUEST: 'GET_CLOSE_RELATION_EDGES_REQUEST',
    GET_CLOSE_RELATION_EDGES_SUCCESS: 'GET_CLOSE_RELATION_EDGES_SUCCESS',
    GET_CLOSE_RELATION_EDGES_FAILURE: 'GET_CLOSE_RELATION_EDGES_FAILURE',

    GET_CLOSE_RELATION_NODES_REQUEST: 'GET_CLOSE_RELATION_NODES_REQUEST',
    GET_CLOSE_RELATION_NODES_SUCCESS: 'GET_CLOSE_RELATION_NODES_SUCCESS',
    GET_CLOSE_RELATION_NODES_FAILURE: 'GET_CLOSE_RELATION_NODES_FAILURE'
}