export const HomeSpaceConstants = {
    GET_LIST_ALL_TOKENS_REQUEST: 'GET_LIST_ALL_TOKENS_REQUEST',
    GET_LIST_ALL_TOKENS_SUCCESS: 'GET_LIST_ALL_TOKENS_SUCCESS',
    GET_LIST_ALL_TOKENS_FAILURE: 'GET_LIST_ALL_TOKENS_FAILURE'
}