export const OverviewDashboardConstants = {
    GET_DASHBOARD_MARKET_CAP_VOLUME_REQUEST: 'GET_DASHBOARD_MARKET_CAP_VOLUME_REQUEST',
    GET_DASHBOARD_MARKET_CAP_VOLUME_SUCCESS: 'GET_DASHBOARD_MARKET_CAP_VOLUME_SUCCESS',
    GET_DASHBOARD_MARKET_CAP_VOLUME_FAILURE: 'GET_DASHBOARD_MARKET_CAP_VOLUME_FAILURE',

    GET_DASHBOARD_MARKET_PLACE_TREND_REQUEST: 'GET_DASHBOARD_MARKET_PLACE_TREND_REQUEST',
    GET_DASHBOARD_MARKET_PLACE_TREND_SUCCESS: 'GET_DASHBOARD_MARKET_PLACE_TREND_SUCCESS',
    GET_DASHBOARD_MARKET_PLACE_TREND_FAILURE: 'GET_DASHBOARD_MARKET_PLACE_TREND_FAILURE',

    GET_DASHBOARD_HOLDER_REQUEST: 'GET_DASHBOARD_HOLDER_REQUEST',
    GET_DASHBOARD_HOLDER_SUCCESS: 'GET_DASHBOARD_HOLDER_SUCCESS',
    GET_DASHBOARD_HOLDER_FAILURE: 'GET_DASHBOARD_HOLDER_FAILURE',

    GET_DASHBOARD_TRADER_REQUEST: 'GET_DASHBOARD_TRADER_REQUEST',
    GET_DASHBOARD_TRADER_SUCCESS: 'GET_DASHBOARD_TRADER_SUCCESS',
    GET_DASHBOARD_TRADER_FAILURE: 'GET_DASHBOARD_TRADER_FAILURE',

    GET_DASHBOARD_AVERAGE_PRICE_REQUEST: 'GET_DASHBOARD_AVERAGE_PRICE_REQUEST',
    GET_DASHBOARD_AVERAGE_PRICE_SUCCESS: 'GET_DASHBOARD_AVERAGE_PRICE_SUCCESS',
    GET_DASHBOARD_AVERAGE_PRICE_FAILURE: 'GET_DASHBOARD_AVERAGE_PRICE_FAILURE',

    GET_DASHBOARD_STAKING_REQUEST: 'GET_DASHBOARD_STAKING_REQUEST',
    GET_DASHBOARD_STAKING_SUCCESS: 'GET_DASHBOARD_STAKING_SUCCESS',
    GET_DASHBOARD_STAKING_FAILURE: 'GET_DASHBOARD_STAKING_FAILURE',
}