export const RelationshipSpaceConstants = {
    GET_TOP_WALLET_RELATIONSHIP_REQUEST: 'GET_TOP_WALLET_RELATIONSHIP_REQUEST',
    GET_TOP_WALLET_RELATIONSHIP_SUCCESS: 'GET_TOP_WALLET_RELATIONSHIP_SUCCESS',
    GET_TOP_WALLET_RELATIONSHIP_FAILURE: 'GET_TOP_WALLET_RELATIONSHIP_FAILURE',

    GET_TOP_CLUSTER_RELATIONSHIP_REQUEST: 'GET_TOP_CLUSTER_RELATIONSHIP_REQUEST',
    GET_TOP_CLUSTER_RELATIONSHIP_SUCCESS: 'GET_TOP_CLUSTER_RELATIONSHIP_SUCCESS',
    GET_TOP_CLUSTER_RELATIONSHIP_FAILURE: 'GET_TOP_CLUSTER_RELATIONSHIP_FAILURE'
}