export const RelationshipSpaceConstants = {
    GET_TOP_WALLET_RELATIONSHIP_REQUEST: 'GET_TOP_WALLET_RELATIONSHIP_REQUEST',
    GET_TOP_WALLET_RELATIONSHIP_SUCCESS: 'GET_TOP_WALLET_RELATIONSHIP_SUCCESS',
    GET_TOP_WALLET_RELATIONSHIP_FAILURE: 'GET_TOP_WALLET_RELATIONSHIP_FAILURE',

    GET_TOP_CLUSTER_RELATIONSHIP_REQUEST: 'GET_TOP_CLUSTER_RELATIONSHIP_REQUEST',
    GET_TOP_CLUSTER_RELATIONSHIP_SUCCESS: 'GET_TOP_CLUSTER_RELATIONSHIP_SUCCESS',
    GET_TOP_CLUSTER_RELATIONSHIP_FAILURE: 'GET_TOP_CLUSTER_RELATIONSHIP_FAILURE',

    GET_TOP_LIST_CLUSTER_REQUEST: 'GET_TOP_LIST_CLUSTER_REQUEST',
    GET_TOP_LIST_CLUSTER_SUCCESS: 'GET_TOP_LIST_CLUSTER_SUCCESS',
    GET_TOP_LIST_CLUSTER_FAILURE: 'GET_TOP_LIST_CLUSTER_FAILURE',
    
    GET_CLUSTER_TOKEN_CHANGE_LOGS_REQUEST: 'GET_CLUSTER_TOKEN_CHANGE_LOGS_REQUEST',
    GET_CLUSTER_TOKEN_CHANGE_LOGS_SUCCESS: 'GET_CLUSTER_TOKEN_CHANGE_LOGS_SUCCESS',
    GET_CLUSTER_TOKEN_CHANGE_LOGS_FAILURE: 'GET_CLUSTER_TOKEN_CHANGE_LOGS_FAILURE',
    
    GET_LINK_DETAIL_REQUEST: 'GET_LINK_DETAIL_REQUEST',
    GET_LINK_DETAIL_SUCCESS: 'GET_LINK_DETAIL_SUCCESS',
    GET_LINK_DETAIL_FAILURE: 'GET_LINK_DETAIL_FAILURE'
}