export const RelationGraphConstants = {
    GET_CLOSE_RELATION_EDGES_REQUEST: 'GET_CLOSE_RELATION_EDGES_REQUEST',
    GET_CLOSE_RELATION_EDGES_SUCCESS: 'GET_CLOSE_RELATION_EDGES_SUCCESS',
    GET_CLOSE_RELATION_EDGES_FAILURE: 'GET_CLOSE_RELATION_EDGES_FAILURE',

    GET_CLOSE_RELATION_NODES_REQUEST: 'GET_CLOSE_RELATION_NODES_REQUEST',
    GET_CLOSE_RELATION_NODES_SUCCESS: 'GET_CLOSE_RELATION_NODES_SUCCESS',
    GET_CLOSE_RELATION_NODES_FAILURE: 'GET_CLOSE_RELATION_NODES_FAILURE',

    GET_RELATIONSHIP_TOKEN_CHANGE_LOGS_REQUEST: 'GET_RELATIONSHIP_TOKEN_CHANGE_LOGS_REQUEST',
    GET_RELATIONSHIP_TOKEN_CHANGE_LOGS_SUCCESS: 'GET_RELATIONSHIP_TOKEN_CHANGE_LOGS_SUCCESS',
    GET_RELATIONSHIP_TOKEN_CHANGE_LOGS_FAILURE: 'GET_RELATIONSHIP_TOKEN_CHANGE_LOGS_FAILURE',
}