export const UserAnalysisConstants = {
    GET_HOLDING_KNIGHT_DISTRIBUTION_REQUEST: 'GET_HOLDING_KNIGHT_DISTRIBUTION_REQUEST',
    GET_HOLDING_KNIGHT_DISTRIBUTION_SUCCESS: 'GET_HOLDING_KNIGHT_DISTRIBUTION_SUCCESS',
    GET_HOLDING_KNIGHT_DISTRIBUTION_FAILURE: 'GET_HOLDING_KNIGHT_DISTRIBUTION_FAILURE',

    GET_HOLDING_ARMOURY_DISTRIBUTION_REQUEST: 'GET_HOLDING_ARMOURY_DISTRIBUTION_REQUEST',
    GET_HOLDING_ARMOURY_DISTRIBUTION_SUCCESS: 'GET_HOLDING_ARMOURY_DISTRIBUTION_SUCCESS',
    GET_HOLDING_ARMOURY_DISTRIBUTION_FAILURE: 'GET_HOLDING_ARMOURY_DISTRIBUTION_FAILURE',

    GET_TRADING_OF_WALLET_REQUEST: 'GET_TRADING_OF_WALLET_REQUEST',
    GET_TRADING_OF_WALLET_SUCCESS: 'GET_TRADING_OF_WALLET_SUCCESS',
    GET_TRADING_OF_WALLET_FAILURE: 'GET_TRADING_OF_WALLET_FAILURE',
}